name: $(Rev:r) # build numbering format

resources:
  - repo: self

jobs:
  - job: "BuildAndPublishToMarketplace"
    displayName: "Build and publish to Marketplace"
    pool:
      name: Azure Pipelines
      vmImage: "windows-latest"
    steps:
      - task: Npm@1
        displayName: "NPM CI"
        inputs:
          command: custom
          verbose: false
          customCommand: ci
          workingDir: NugetVulnerabilityScanTask

      - powershell: |
          $filePath= Join-Path -Path $(Build.Repository.LocalPath) -ChildPath "NugetVulnerabilityScanTask\package.json"

          Write-Host "Repository LocalPath: $(Build.Repository.LocalPath)"
          Write-Host "Environment-File: $filePath"
          Write-Host "Build Number: $(Build.BuildNumber)"
          $environmentContent = Get-Content $filePath
          $replaced = $environmentContent -replace '__BuildVersion__', '$(Build.BuildNumber)'
          Set-Content -Path $filePath -value $replaced
        displayName: "Update Version - NPM"

      - powershell: |
          $filePath= Join-Path -Path $(Build.Repository.LocalPath) -ChildPath "\NugetVulnerabilityScanTask\task.json"

          Write-Host "Repository LocalPath: $(Build.Repository.LocalPath)"
          Write-Host "Environment-File: $filePath"
          Write-Host "Build Number: $(Build.BuildNumber)"
          $environmentContent = Get-Content $filePath
          $replaced = $environmentContent -replace '__BuildVersion__', '$(Build.BuildNumber)'
          Set-Content -Path $filePath -value $replaced
        displayName: "Update Version - Task"

      - task: Npm@1
        displayName: "Build"
        inputs:
          command: custom
          verbose: false
          customCommand: "run ci-build"

      - task: ms-devlabs.vsts-developer-tools-build-tasks.tfx-installer-build-task.TfxInstaller@3
        displayName: "Use Node CLI for Azure DevOps (tfx-cli)"

      - task: ms-devlabs.vsts-developer-tools-build-tasks.publish-extension-build-task.PublishAzureDevOpsExtension@3
        displayName: "Publish Extension"
        inputs:
          connectedServiceName: "Windows Marketplace"
          updateTasksVersion: false
